"use client";

import {
  BrainCircuit,
  ShieldCheck,
  TriangleAlert,
  Lightbulb,
} from "lucide-react";

interface Props {
  data: any;
}

export default function AIExecutiveReport({
  data,
}: Props) {
  return (
    <div className="rounded-3xl border border-slate-800 bg-slate-900 p-8 shadow-xl">

      <div className="flex items-center gap-3 mb-8">

        <div className="rounded-xl bg-emerald-500/20 p-3">

          <BrainCircuit className="text-emerald-400" />

        </div>

        <div>

          <h2 className="text-2xl font-bold text-white">
            AI Executive Report
          </h2>

          <p className="text-slate-400">
            Restaurant performance generated by Gemini AI
          </p>

        </div>

      </div>

      <div className="rounded-2xl bg-slate-800 p-6">

        <h3 className="text-lg font-semibold text-white mb-3">
          Executive Summary
        </h3>

        <p className="text-slate-300 leading-8">
          {data?.summary ??
            "AI summary unavailable."}
        </p>

      </div>

      <div className="grid lg:grid-cols-2 gap-6 mt-8">

        <div className="rounded-2xl bg-slate-800 p-6">

          <div className="flex items-center gap-2 mb-4">

            <ShieldCheck className="text-green-400" />

            <h3 className="text-lg font-semibold text-white">
              Strengths
            </h3>

          </div>

          <ul className="space-y-3">

            {(data?.strengths || []).map(
              (item: string, index: number) => (
                <li
                  key={index}
                  className="text-slate-300"
                >
                  ✅ {item}
                </li>
              )
            )}

          </ul>

        </div>

        <div className="rounded-2xl bg-slate-800 p-6">

          <div className="flex items-center gap-2 mb-4">

            <TriangleAlert className="text-yellow-400" />

            <h3 className="text-lg font-semibold text-white">
              Risks
            </h3>

          </div>

          <ul className="space-y-3">

            {(data?.risks || []).map(
              (item: string, index: number) => (
                <li
                  key={index}
                  className="text-slate-300"
                >
                  ⚠ {item}
                </li>
              )
            )}

          </ul>

        </div>

      </div>

      <div className="mt-8 rounded-2xl border border-emerald-500/20 bg-emerald-500/10 p-6">

        <div className="flex items-center gap-2 mb-4">

          <Lightbulb className="text-emerald-400" />

          <h3 className="text-lg font-semibold text-white">
            AI Recommendation
          </h3>

        </div>

        <p className="text-slate-300 leading-7">
          {data?.recommendation}
        </p>

      </div>

    </div>
  );
}